# Generated by Django 5.0.1 on 2024-01-20 11:20

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('train_datasets_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeuralNetworkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TrainedNeuralNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file_path', models.CharField(max_length=500)),
                ('started_training_at', models.DateTimeField(default=datetime.datetime.now)),
                ('finished_training_at', models.DateTimeField(blank=True, null=True)),
                ('neural_network_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='model_training.neuralnetworktype')),
                ('train_dataset', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='train_datasets_manager.traindataset')),
            ],
        ),
    ]
