# Generated by Django 5.0.1 on 2024-01-20 11:58

import video_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inferencevideo',
            name='file_path',
            field=models.FileField(upload_to=video_manager.models.inference_video_upload_path),
        ),
    ]
